# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AppBucket - It’s All About "Doing Things"
email: abednarski79@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#  AppBucket | The one person maker club
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://projects.appbucket.com" # the base hostname & protocol for your site
# twitter_username: abednarski79
github_username:  abednarski79

# Build settings
markdown: kramdown

kramdown:
  input: GFM
